# Generated by Django 3.0.5 on 2020-05-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(to='hamburguesa.Ingrediente'),
        ),
    ]
