# Generated by Django 3.0.5 on 2020-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0002_auto_20200502_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteEnHamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamburguesa_id', models.IntegerField()),
                ('ingrediente_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='hamburguesa',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
