# Generated by Django 3.0.5 on 2020-05-03 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesa', '0003_auto_20200502_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteenhamburguesa',
            name='hamburguesa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamburguesa.Hamburguesa'),
        ),
        migrations.AlterField(
            model_name='ingredienteenhamburguesa',
            name='ingrediente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamburguesa.Ingrediente'),
        ),
    ]
